### ISSUE TITLE
Error: can't open input file /tmp/tmpkm_<x>/contig_<x>.fa. with version 1.01

### ISSUE THREAD

**Issue by ohickl** [BigDataBiology/SemiBin#101]
Hi,
I get a similar error as the one from #93 with version 1.0.1 during coassembly as well as single sample `single_easy` binning, e.g.:
```
+ SemiBin -v
1.0.1
+ SemiBin single_easy_bin --input-fasta <fasta>
                          --input-bam <1.bam> <2.bam> <3.bam> <4.bam> <5.bam> <6.bam> <7.bam> <8.bam> <9.bam>
                          --threads 64
                          --random-seed 0
                          --reference-db-data-dir <gtdb_db>
                          --output <out_dir>
2022-07-07 11:12:25,912 - Generate training data.
2022-07-07 11:12:46,422 - Calculating coverage for every sample.
2022-07-07 11:12:46,424 - Processing ...
...
2022-07-07 11:15:41,142 - Start generating kmer features from fasta file.
2022-07-07 11:21:47,376 - Running mmseqs and generate cannot-link file.
2022-07-07 11:21:48,170 - Found GTDB directory: `.../gtdb_semibin/`.
createdb /tmp/tmp6neo93dj/SemiBinFiltered.fa /tmp/tmp6neo93dj/contig_DB

MMseqs Version:                         13.45111
First sequence as representative        false
Target column                           1
Add full header                         false
Sequence source                         0
Database output                         false
Threads                                 128
Compressed                              0
Verbosity                               3

Time for merging to taxonomyResult.tsv: 0h 0m 0s 159ms
Time for processing: 0h 0m 0s 519ms
2022-07-07 11:51:56,185 - Training model and clustering.
2022-07-07 11:51:56,474 - Start training from one sample.
2022-07-07 11:51:58,550 - Training model...
^M  0%|          | 0/20 [00:00<?, ?it/s]^M  0%|          | 0/20 [03:29<?, ?it/s]
Traceback (most recent call last):
  File ".../SemiBin", line 10, in <module>
    sys.exit(main())
  File ".../SemiBin/main.py", line 1040, in main
    single_easy_binning(
  File ".../SemiBin/main.py", line 860, in single_easy_binning
    training(logger, [args.contig_fasta],
  File ".../SemiBin/main.py", line 761, in training
    model = train(
  File ".../SemiBin/semi_supervised_model.py", line 170, in train
    seed = cal_num_bins(
  File ".../SemiBin/utils.py", line 382, in cal_num_bins
    contig_output = run_orffinder(fasta_path, num_process, tdir)
  File ".../SemiBin/utils.py", line 335, in run_prodigal
    f.write(open(os.path.join(output, 'contig_{}.faa'.format(index)), 'r').read())
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmplf_sjmek/contig_60.faa'
```

I tried with version 0.7.0, which seems to work for single samples but not coassemblies:
```
...
2022-04-22 16:27:43,039 - Start generating kmer features from fasta file.
2022-04-22 16:33:59,619 - Start binning.
Semi_encoding_single(
  (encoder1): Sequential(
    (0): Linear(in_features=136, out_features=512, bias=True)
    (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): LeakyReLU(negative_slope=0.01)
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=512, out_features=512, bias=True)
    (5): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): LeakyReLU(negative_slope=0.01)
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=512, out_features=100, bias=True)
  )
  (decoder1): Sequential(
    (0): Linear(in_features=100, out_features=512, bias=True)
    (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): LeakyReLU(negative_slope=0.01)
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=512, out_features=512, bias=True)
    (5): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): LeakyReLU(negative_slope=0.01)
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=512, out_features=136, bias=True)
    (9): Softmax(dim=1)
  )
)
tensor([[2.9161e-02, 2.2513e-02, 1.6736e-02,  ..., 1.0659e-01, 2.1843e-02,
         1.0000e-07],
        [1.9267e-02, 1.3116e-02, 1.1914e-02,  ..., 3.0592e-02, 5.2389e-03,
         1.0000e-07],
        [2.0920e-02, 1.4588e-02, 1.4779e-02,  ..., 3.2391e-02, 6.8474e-03,
         1.0000e-07],
        ...,
        [3.6168e-02, 2.1505e-02, 1.8573e-02,  ..., 3.4844e-02, 3.9726e-02,
         1.0000e-07],
        [2.5338e-02, 2.0829e-02, 1.4387e-02,  ..., 2.9561e-02, 1.0000e-07,
         1.0000e-07],
        [3.0988e-02, 2.4209e-02, 1.7753e-02,  ..., 2.5341e-02, 1.0000e-07,
         1.0000e-07]], dtype=torch.float64)
torch.Size([19724, 145])
Traceback (most recent call last):
  File ".../SemiBin", line 10, in <module>
    sys.exit(main())
  File ".../SemiBin/main.py", line 1040, in main
    single_easy_binning(
  File ".../SemiBin/main.py", line 865, in single_easy_binning
    binning(logger, args.num_process, data_path,
  File ".../SemiBin/main.py", line 810, in binning
    cluster(
  File ".../SemiBin/cluster.py", line 111, in cluster
    embedding = model.embedding(x.float()).detach().cpu().numpy()
  File ".../SemiBin/semi_supervised_model.py", line 89, in embedding
    return self.encoder1(input)
  File ".../torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File ".../torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File ".../torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File ".../torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File ".../torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (19724x145 and 136x512)
```

Best

Oskar

**Comment by luispedro** [comment]
Conda is up t odate now

**Comment by luispedro** [comment]
Conda is up to date now:

https://anaconda.org/bioconda/SemiBin

**Comment by ohickl** [comment]
Works now with both single samples and coassemblies using conda. Great, thanks!
