### ISSUE TITLE
Error during coverage calculation

### ISSUE THREAD

**Issue by rhysnewell** [BigDataBiology/SemiBin#103]
Hello!

I'm just trying out SemiBin v1.0.2 which fixed a lot of the errors I was having with mmseqs, however I have come across a new error when using a command akin to: 
`SemiBin single_easy_bin -i final_contigs.fasta -b data/binning_bams/*.bam -o data/semibin_bins -p 36`

This command produces this error:
```
2022-07-13 13:52:43,405 - Generate training data.
2022-07-13 13:52:47,987 - Calculating coverage for every sample.
2022-07-13 13:52:47,988 - Processing `data/binning_bams/final_contigs.fasta.SRR11673988_1.fastq.gz.bam`
2022-07-13 13:52:47,988 - Processing `data/binning_bams/final_contigs.fasta.SRR11674045_R1.fastq.gz.bam`
Traceback (most recent call last):
  File "/home/n10853499/.conda/envs/ec9f4fff01cf465c9582bfc321d2e00a/lib/python3.9/site-packages/SemiBin/error.py", line 18, in __call__                                                                        result = self.__callable(*args, **kwargs)  File "/home/n10853499/.conda/envs/ec9f4fff01cf465c9582bfc321d2e00a/lib/python3.9/site-packages/SemiBin/generate_coverage.py", line 120, in generate_cov
contig_cov = calculate_coverage(bed_p.stdout, bam_file, threshold, is_combined=is_combined, sep = sep, 
File "/home/n10853499/.conda/envs/ec9f4fff01cf465c9582bfc321d2e00a/lib/python3.9/site-packages/SemiBin/generate_coverage.py", line 32, in calculate_coverage                                                  value = int(line_split[3])
ValueError: invalid literal for int() with base 10: '1.18849e+06'

2022-07-13 14:27:45,781 - Processed:data/binning_bams/final_contigs.fasta.SRR11673988_1.fastq.gz.bam
Error: Generating coverage file fail
```

Looks like it's trying to read a string "1.18849e+06" and directly convert that to an integer. A quick and easy way to avoid this would be to read it in as a float first i.e. float(line_split[3]) and then you can convert it to an int if you need to. 

Alternatively, have you considered allowing the user the specify CoverM/jgi_summarize_contig_depths -esque input as opposed to always generating contig coverages yourself?

Cheers,
Rhys

**Comment by psj1997** [comment]
Hi

Thanks for your attention of SemiBin.

I have fixed this and you can install SemiBin from source and rerun it.

`Alternatively, have you considered allowing the user the specify CoverM/jgi_summarize_contig_depths -esque input as opposed to always generating contig coverages yourself?`
This is because we need to calculate the coverage of the must-link pair (split the contig) that used in the model training, so we can not use CoverM/jgi_summarize_contig_depths.

Sincerely
Shaojun

**Comment by hildebra** [comment]
Just a question, since I would find this option also very useful: if I only use pre-trained SemiBin models, would in this case external coverage files (output from bedtools or jgi_summarize_contig_depths) work? 
thanks, Falk

**Comment by psj1997** [comment]
Yes. 

With pretrained models, for the coverage part we need the mean and variance value, so the output from jgi_summarize_contig_depths works. 
We will update later for this part that SemiBin can use outputs from jgi_summarize_contig_depths as inputs in this mode.

Sincerely
Shaojun

**Comment by rhysnewell** [comment]
The fix you added works, no more error so closing this now. Support for jgi like coverage output when not using a pretrained model would be great, but no rush.

Cheers,
Rhys

**Comment by hildebra** [comment]
Cheers Shaojun,
will be waiting for the jgi_depth update currently to implement into our main pipeline in the lab then, very exciting software!
best, Falk
