### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by palomo11** [BigDataBiology/SemiBin#108]
Hi, I'm running single-easy mode using a co-assembly and I got the following error:

```
2022-08-11 15:57:07,511 - Do not detect GPU. Running with CPU.
2022-08-11 15:57:11,364 - Generate training data.
2022-08-11 15:57:21,906 - Calculating coverage for every sample.
2022-08-11 15:57:21,908 - Processing `./metabat2_Pond_coassembly/work_files/Sample1.bam`
2022-08-11 15:57:21,908 - Processing `./metabat2_Pond_coassembly/work_files/Sample2.bam`
2022-08-11 15:57:21,908 - Processing `./metabat2_Pond_coassembly/work_files/Sample3.bam`
2022-08-11 15:57:21,908 - Processing `./metabat2_Pond_coassembly/work_files/Sample4.bam`
2022-08-11 15:57:21,908 - Processing `./metabat2_Pond_coassembly/work_files/Sample6.bam`
2022-08-11 16:03:45,590 - Processed:./metabat2_Pond_coassembly/work_files/Sample4.bam
2022-08-11 16:03:56,073 - Processed:./metabat2_Pond_coassembly/work_files/Sample3.bam
2022-08-11 16:04:04,254 - Processed:./metabat2_Pond_coassembly/work_files/Sample1.bam
2022-08-11 16:04:08,450 - Processed:./metabat2_Pond_coassembly/work_files/Sample2.bam
2022-08-11 16:04:13,517 - Processed:./metabat2_Pond_coassembly/work_files/Sample6.bam
2022-08-11 16:04:13,700 - Start generating kmer features from fasta file.
2022-08-11 16:13:24,676 - Running mmseqs and generate cannot-link file.
2022-08-11 16:13:28,063 - Found GTDB directory: `/work/ese-alexp/databases/SemiBin_GTDB`.
2022-08-11 17:51:54,906 - Training model and clustering.
2022-08-11 17:51:54,986 - Start training from one sample.
2022-08-11 17:52:05,058 - Training model...
  0%|          | 0/20 [00:00<?, ?it/s]2022-08-11 18:03:11,618 - Generate training data of 0:
2022-08-11 18:03:25,761 - Number of must link pair:60387
2022-08-11 18:03:25,767 - Number of can not link pair:4017766
100%|██████████| 20/20 [1:28:26<00:00, 265.31s/it]
2022-08-11 19:20:31,605 - Training finished.
2022-08-11 19:20:33,251 - Start binning.
Traceback (most recent call last):
  File "/work/ese-alexp/software/python/anaconda3/2021.11/envs/SemiBin/bin/SemiBin", line 10, in <module>
    sys.exit(main())
  File "/work/ese-alexp/software/python/anaconda3/2021.11/envs/SemiBin/lib/python3.9/site-packages/SemiBin/main.py", line 1065, in main
    single_easy_binning(
  File "/work/ese-alexp/software/python/anaconda3/2021.11/envs/SemiBin/lib/python3.9/site-packages/SemiBin/main.py", line 875, in single_easy_binning
    binning(logger, args.num_process, data_path,
  File "/work/ese-alexp/software/python/anaconda3/2021.11/envs/SemiBin/lib/python3.9/site-packages/SemiBin/main.py", line 820, in binning
    cluster(
  File "/work/ese-alexp/software/python/anaconda3/2021.11/envs/SemiBin/lib/python3.9/site-packages/SemiBin/cluster.py", line 92, in cluster
    from igraph import Graph
  File "/work/ese-alexp/software/python/anaconda3/2021.11/envs/SemiBin/lib/python3.9/site-packages/igraph/__init__.py", line 26, in <module>
    from igraph._igraph import (
ImportError: /work/ese-alexp/software/python/anaconda3/2021.11/envs/SemiBin/lib/python3.9/site-packages/igraph/../../.././libgfortran.so.5: invalid ELF header
```

Any idea about what is going on?

it seems data_split.csv, taxonomyResult.tsv, cannot.txt and markers.hmmout were properly generated.

Thanks in advance.

**Comment by psj1997** [comment]
Hi

Can you list the version of all dependencies? I can try to check it. 

Sincerely
Shaojun

**Comment by palomo11** [comment]
Hi Shaojun, 

here it is:

Package            Version
------------------ -----------
atomicwrites       1.4.1
brotlipy           0.7.0
certifi            2022.6.15
cffi               1.15.1
charset-normalizer 2.1.0
colorama           0.4.5
cryptography       37.0.4
future             0.18.2
idna               3.3
igraph             0.9.11
joblib             1.1.0
numexpr            2.7.3
numpy              1.23.1
pandas             1.4.3
pip                22.2.2
pycparser          2.21
pyOpenSSL          22.0.0
PySocks            1.7.1
python-dateutil    2.8.2
pytz               2022.1
PyYAML             6.0
requests           2.28.1
scikit-learn       1.1.2
scipy              1.9.0
SemiBin            1.0.3
setuptools         63.4.2
six                1.16.0
texttable          1.6.4
threadpoolctl      3.1.0
torch              1.8.0.post3
tqdm               4.64.0
typing_extensions  4.3.0
urllib3            1.26.11
wheel              0.37.1

Thanks for your help.

**Comment by luispedro** [comment]
@palomo11: Reading through the error messages, I think this is an issue with your installation that we cannot really solve. I would try reinstalling the packages as my guess is that something went wrong during the installation (maybe a lack of disk space or similar issue). Thus, I am closing the issue here

**Comment by palomo11** [comment]
Thanks for the advice. I installed it again and I have no issues now.
