### ISSUE TITLE
OSError: Failure in running bedtools AND BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by PeterCx** [BigDataBiology/SemiBin#110]
Hi there,

I am trying to run SemiBin with the following command:

SemiBin multi_easy_bin -i concatenated.fa -b *.bam -o SemiBin/

But I am encountering the following errors:

Traceback (most recent call last):
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/site-packages/SemiBin/error.py", line 18, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/site-packages/SemiBin/generate_coverage.py", line 103, in generate_cov
    raise OSError("Failure in running bedtools")
**OSError: Failure in running bedtools**

Process ForkPoolWorker-40:
Traceback (most recent call last):
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
**BrokenPipeError: [Errno 32] Broken pipe**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/site-packages/SemiBin/error.py", line 18, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/peterc/miniconda3/envs/semibin_env/lib/python3.9/site-packages/SemiBin/generate_coverage.py", line 103, in generate_cov
    raise OSError("Failure in running bedtools")
OSError: Failure in running bedtools

Help greatly appreciated.

Kind regards,

P

**Comment by psj1997** [comment]
Hi, thanks for your attention of SemiBin.

Can you try to run with ` -p 1 ` using one process to deal with the bams. It seems the error is caused by the multiprocessing.

Sincerely
Shaojun

**Comment by PeterCx** [comment]
Thank you for getting back so quick.

This SOLVED the issue. Many thanks
