### ISSUE TITLE
How to install SemiBin on a server without network

### ISSUE THREAD

**Issue by huizhen-yan** [BigDataBiology/SemiBin#118]
Hi,
I tried to run SemiBin on my computer, but failed. Maybe it's out of memory. So I want to re-install SemiBin on a larger server without network. Could you tell me how to install without network?

``
(SemiBin) yanhz@yanhz:~/data2t/2019mei7/SemiBin$ SemiBin single_easy_bin -i /home/yanhz/data2t/2019mei7/yhzm7_megahit/yhzm7_final.contigs.fa -b /home/yanhz/data2t/2019mei7/yhzm7_megahit/yhzm7.S4R1.sort.bam --environment ocean -o semibin_singleS4R1_output
2022-10-15 19:23:10,744 - Setting number of CPUs to 12
2022-10-15 19:23:10,744 - Do not detect GPU. Running with CPU.
2022-10-15 19:23:15,753 - Generate training data.
2022-10-15 19:23:16,314 - Calculating coverage for every sample.
2022-10-15 19:23:16,315 - Processing `/home/yanhz/data2t/2019mei7/yhzm7_megahit/yhzm7.S4R1.sort.bam`
2022-10-15 19:28:54,999 - Processed:/home/yanhz/data2t/2019mei7/yhzm7_megahit/yhzm7.S4R1.sort.bam
2022-10-15 19:28:55,115 - Start generating kmer features from fasta file.
2022-10-15 19:45:45,764 - Start binning.
2022-10-15 20:24:18,357 - Calculating depth matrix.
Traceback (most recent call last):
  File "/home/yanhz/miniconda2/envs/SemiBin/bin/SemiBin", line 10, in <module>
    sys.exit(main())
  File "/home/yanhz/miniconda2/envs/SemiBin/lib/python3.10/site-packages/SemiBin/main.py", line 1167, in main
    single_easy_binning(
  File "/home/yanhz/miniconda2/envs/SemiBin/lib/python3.10/site-packages/SemiBin/main.py", line 950, in single_easy_binning
    binning(logger, args.num_process, data_path,
  File "/home/yanhz/miniconda2/envs/SemiBin/lib/python3.10/site-packages/SemiBin/main.py", line 879, in binning
    cluster(
  File "/home/yanhz/miniconda2/envs/SemiBin/lib/python3.10/site-packages/SemiBin/cluster.py", line 148, in cluster
    kl = cal_kl(depth[:,2*k], depth[:, 2*k + 1])
  File "/home/yanhz/miniconda2/envs/SemiBin/lib/python3.10/site-packages/SemiBin/cluster.py", line 53, in cal_kl
    res = ne.evaluate(
  File "/home/yanhz/miniconda2/envs/SemiBin/lib/python3.10/site-packages/numexpr/necompiler.py", line 827, in evaluate
    return compiled_ex(*arguments, **kwargs)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 354. GiB for an array with shape (308142, 308142) and data type float32
(SemiBin) yanhz@yanhz:~/data2t/2019mei7/SemiBin$
``

![481665838807_ pic_hd](https://user-images.githubusercontent.com/71927771/195987740-23719c91-3680-40f4-8c07-a3761ddf88a8.jpg)

**Comment by psj1997** [comment]
You can try to install the dependencies and SemiBin from source.

Sincerely
Shaojun
