### ISSUE TITLE
Running `bedtools genomecov` failed

### ISSUE THREAD

**Issue by nashanghenzan** [BigDataBiology/SemiBin#131]
i am sure my bam files have been sorted, but when i enter 
```
SemiBin multi_easy_bin \
-i /mnt/zuzhuang/F1/contigs/output/concatenated.fa \
-b GHB.mapped.sorted.bam GHR.mapped.sorted.bam GSB.mapped.sorted.bam GSR.mapped.sorted.bam LHB.mapped.sorted.bam LHR.mapped.sorted.bam LSB.mapped.sorted.bam LSR.mapped.sorted.bam PHB.mapped.sorted.bam PHR.mapped.sorted.bam PSB.mapped.sorted.bam PSR.mapped.sorted.bam SHB.mapped.sorted.bam SHR.mapped.sorted.bam SSB.mapped.sorted.bam SSR.mapped.sorted.bam THB.mapped.sorted.bam THR.mapped.sorted.bam TSB.mapped.sorted.bam TSR.mapped.sorted.bam \
-o /mnt/semibin/multi_output --self-supervised
```
it show:
```
2023-04-25 17:25:46 centos7-02-66b664b9d9-gz85w SemiBin[13084] INFO Setting number of CPUs to 16
2023-04-25 17:25:46 centos7-02-66b664b9d9-gz85w SemiBin[13084] INFO Binning for short_read
2023-04-25 17:25:58 centos7-02-66b664b9d9-gz85w SemiBin[13084] INFO Did not detect GPU, using CPU.
2023-04-25 17:25:58 centos7-02-66b664b9d9-gz85w SemiBin[13084] INFO Performing multi-sample binning
2023-04-25 17:25:58 centos7-02-66b664b9d9-gz85w SemiBin[13084] INFO Generating training data...
2023-04-25 17:28:40 centos7-02-66b664b9d9-gz85w SemiBin[13084] INFO Calculating coverage for every sample.
2023-04-25 17:31:13 centos7-02-66b664b9d9-gz85w SemiBin[13131] CRITICAL Running `bedtools genomecov` failed. Please check your input files: SemiBin expects that they are sorted BAM files.
Traceback (most recent call last):
  File "/root/miniconda3/envs/semibin/lib/python3.11/site-packages/SemiBin/error.py", line 18, in __call__
    result = self.__callable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/semibin/lib/python3.11/site-packages/SemiBin/generate_coverage.py", line 104, in generate_cov
    raise OSError("Failure in running bedtools")
OSError: Failure in running bedtools
```

**Comment by luispedro** [comment]
Thank you for the report. I cannot see that you are doing anything wrong

If you run the following, do you get an error? What is the output

```bash
bedtools genomecov -bga -ibam GHB.mapped.sorted.bam >/dev/null
echo $?
```

(The `echo $?` command should print the result of the last command and, if it was successful, it should be `0`)

**Comment by nashanghenzan** [comment]
> Thank you for the report. I cannot see that you are doing anything wrong
> 
> If you run the following, do you get an error? What is the output
> 
> ```shell
> bedtools genomecov -bga -ibam GHB.mapped.sorted.bam >/dev/null
> echo $?
> ```
> 
> (The `echo $?` command should print the result of the last command and, if it was successful, it should be `0`)

hi, just now i try it , it shows:
```
(semibin) [root@centos7-02-66b664b9d9-gz85w test]# bedtools genomecov -bga -ibam PHB.mapped.sorted.bam  > /dev/null        
(semibin) [root@centos7-02-66b664b9d9-gz85w test]# echo $?
0
```

**Comment by nashanghenzan** [comment]
> > Thank you for the report. I cannot see that you are doing anything wrong
> > If you run the following, do you get an error? What is the output
> > ```shell
> > bedtools genomecov -bga -ibam GHB.mapped.sorted.bam >/dev/null
> > echo $?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (The `echo $?` command should print the result of the last command and, if it was successful, it should be `0`)
> 
> hi, just now i try it , it shows:
> 
> ```
> (semibin) [root@centos7-02-66b664b9d9-gz85w test]# bedtools genomecov -bga -ibam PHB.mapped.sorted.bam  > /dev/null        
> (semibin) [root@centos7-02-66b664b9d9-gz85w test]# echo $?
> 0
> ```

that maybe caused by memory limit, use -p 10 to solve
