### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Sumsarium** [BigDataBiology/SemiBin#133]
Hi. 
I keep getting the same KeyError (same error on three different HPCs).

My cmd:

```
conda activate SemiBin
SemiBin \
single_easy_bin \
-i $metagenome \
--input-bam $temp/$assemblyName/*.bam \
--output $temp/$assemblyName/semibin \
--sequencing-type=long_read
```

The error:
```
2023-05-01 23:49:58 XXX SemiBin[2555720] INFO Training model and clustering.
2023-05-01 23:49:58 XXX SemiBin[2555720] INFO Start training from one sample.
2023-05-01 23:50:00 XXX SemiBin[2555720] INFO Training model...
  0%|                                                                                                                         | 0/15 [29:31<?, ?it/s]
Traceback (most recent call last):
  File "/home/XXX/miniconda3/envs/SemiBin/bin/SemiBin", line 10, in <module>
    sys.exit(main1())
  File "/home/XXX/miniconda3/envs/SemiBin/lib/python3.9/site-packages/SemiBin/main.py", line 1482, in main1
    main2(args, is_semibin2=False)
  File "/home/XXX/miniconda3/envs/SemiBin/lib/python3.9/site-packages/SemiBin/main.py", line 1455, in main2
    single_easy_binning(
  File "/home/XXX/miniconda3/envs/SemiBin/lib/python3.9/site-packages/SemiBin/main.py", line 1151, in single_easy_binning
    training(logger, [args.contig_fasta],
  File "/home/XXX/miniconda3/envs/SemiBin/lib/python3.9/site-packages/SemiBin/main.py", line 990, in training
    model = train(
  File "/home/XXX/miniconda3/envs/SemiBin/lib/python3.9/site-packages/SemiBin/semi_supervised_model.py", line 218, in train
    train_input_1.append(train_data_input[contig2ix[str(link[0])]])
KeyError: '1298'
```

Any thoughts?

**Comment by psj1997** [comment]
Hi

Thanks for your attention of SemiBin.

Do you mind sharing the contig id in cannot.txt and contig file? It seems they are not inconsistent.

Another way is that maybe you can try:
`conda activate SemiBin
SemiBin \
single_easy_bin \
-i $metagenome \
--input-bam $temp/$assemblyName/*.bam \
--output $temp/$assemblyName/semibin \
--sequencing-type=long_read
--self-supervised
`

Sincerely
Shaojun

**Comment by luispedro** [comment]
@Sumsarium Did you find a solution? Or could you perhaps share some of your inputs with Shaojun so we could check ourselves?

**Comment by Sumsarium** [comment]
@luispedro  @psj1997 Thanks and sorry for the overdue reply - I plan to look into it later this week. I will let you know as soon as I have some info / files.

**Comment by psj1997** [comment]
Hi, can you check the data.csv file in the output_dir? It seems it is a empty file.

Sincerely
Shaojun

**Comment by luispedro** [comment]
We just released version 2, which includes a more error checking and better diagnostics; so I am closing this here, but please feel free to re-open if it still relevant.
