### ISSUE TITLE
Cannot run on CAMI Skin / VAMB

### ISSUE THREAD

**Issue by richardlett** [BigDataBiology/SemiBin#135]
I am comparing binners, and am using the concatenated assembly from VAMB's CodeOcean repo for reproducibility reasons, obtainable from 

https://codeocean.com/capsule/1017583/tree/v1 

under `data/skin`. Original reads are from CAMI site.

Its uses 'C' as the sample/contig name separator:
```
>S18C13
ACTGGACGATATGCGGCGGCTGGTTGACCGTATCCCGCCGGAGATTTTAGCGGAACTGAA
```

I ran with the `-s C` to   set the separator

```
SemiBin multi_easy_bin -i contigs.fna -b bwa/*.bam  --prodigal-output-faa proteins.faa  -r $SCRATCH/semibincache/ -o semibinout4 -s C
```

and it eventually resulted in this output

```
2023-05-17 11:44:48 nid003592 SemiBin[24123] INFO Start training from one sample.
2023-05-17 11:44:48 nid003592 SemiBin[24123] INFO Training model...
  0%|                                                                                                      | 0/15 [05:29<?, ?it/s]
Traceback (most recent call last):
  File "/pscratch/sd/r/richardl/semibin/bin/SemiBin", line 10, in <module>
    sys.exit(main1())
             ^^^^^^^
  File "/pscratch/sd/r/richardl/semibin/lib/python3.11/site-packages/SemiBin/main.py", line 1482, in main1
    main2(args, is_semibin2=False)
  File "/pscratch/sd/r/richardl/semibin/lib/python3.11/site-packages/SemiBin/main.py", line 1468, in main2
    multi_easy_binning(
  File "/pscratch/sd/r/richardl/semibin/lib/python3.11/site-packages/SemiBin/main.py", line 1236, in multi_easy_binning
    training(logger, [sample_fasta], args.num_process,
  File "/pscratch/sd/r/richardl/semibin/lib/python3.11/site-packages/SemiBin/main.py", line 990, in training
    model = train(
            ^^^^^^
  File "/pscratch/sd/r/richardl/semibin/lib/python3.11/site-packages/SemiBin/semi_supervised_model.py", line 171, in train
    seed = cal_num_bins(
           ^^^^^^^^^^^^^
  File "/pscratch/sd/r/richardl/semibin/lib/python3.11/site-packages/SemiBin/utils.py", line 427, in cal_num_bins
    return get_marker(hmm_output, fasta_path, binned_length, multi_mode, orf_finder=orf_finder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pscratch/sd/r/richardl/semibin/lib/python3.11/site-packages/SemiBin/utils.py", line 346, in get_marker
    data = data[data['contig'].map(lambda c: contig_len[c] >= min_contig_len)]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pscratch/sd/r/richardl/semibin/lib/python3.11/site-packages/pandas/core/series.py", line 4539, in map
    new_values = self._map_values(arg, na_action=na_action)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pscratch/sd/r/richardl/semibin/lib/python3.11/site-packages/pandas/core/base.py", line 890, in _map_values
    new_values = map_f(values, mapper)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "/pscratch/sd/r/richardl/semibin/lib/python3.11/site-packages/SemiBin/utils.py", line 346, in <lambda>
    data = data[data['contig'].map(lambda c: contig_len[c] >= min_contig_len)]
                                             ~~~~~~~~~~^^^
KeyError: 'S17C66326'
```

**Comment by psj1997** [comment]
Hi

Thanks for your attention of SemiBin.

How do you get the file: proteins.faa? It seems that the contig id in proteins.faa does not  match that in corresponding contig file.

You can try to remove the `--prodigal-output-faa proteins.faa` parameter.

Sincerely
Shaojun

**Comment by richardlett** [comment]
I will try that later today.  I used `pprodigal`, which  is a python `prodigal` wrapper to enable multi-threading.

```
pprodigal -i contigs.fna -o proteins.fna  -a proteins.faa -T 256 -C 500 -p meta
```

`-T 256` spawns at most 256 `prodigal` processes, `-C 500` denotes how  many contigs are assigned per task.

**Comment by richardlett** [comment]
Apologies for delay, that fixed it.
