### ISSUE TITLE
SemiBin crashes when the last batch has only one element

### ISSUE THREAD

**Issue by fplazaonate** [BigDataBiology/SemiBin#137]
Hi Luis and Shaojun,

SemiBin crashes when the last batch has only one element i.e dataset_size modulo batch_size = 1
It produces the following error:
```
Traceback (most recent call last):
  File "miniconda3/envs/semibin_env/bin/SemiBin", line 10, in <module>
    sys.exit(main())
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/SemiBin/main.py", line 1362, in main
    single_easy_binning(
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/SemiBin/main.py", line 1092, in single_easy_binning
    training(logger, None,
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/SemiBin/main.py", line 936, in training
    model = train_self(output,
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/SemiBin/self_supervised_model.py", line 126, in train_self
    embedding1, embedding2 = model.forward(
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/SemiBin/semi_supervised_model.py", line 42, in forward
    return self.encoder1(input1), self.encoder1(input2)
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/torch/nn/functional.py", line 2448, in batch_norm
    _verify_batch_size(input.size())
  File "miniconda3/envs/semibin_env/lib/python3.9/site-packages/torch/nn/functional.py", line 2416, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])
```
If relevant, removing the last item of the dataset might be the solution.
Adding the option drop_last=T to the DataLoader will probably fix this but I guess it is not a good solution to ignore at most 512 contigs.

Best,
Florian

**Comment by psj1997** [comment]
We add the drop_last = True when generating the batches.

Sincerely
Shaojun
