### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by ZarulHanifah** [BigDataBiology/SemiBin#139]
Hello SemiBin developers,

I was trying to run this code, which is supposedly the multisample binning on a coassembly:
```
SemiBin2 single_easy_bin \
-i /home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/semibin/coassembly1/concatenated.fa \
-b /home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D5R.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D1R.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/H5B.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/H2B.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/H3B.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D3B.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/H4B.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D4B.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D2B.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D5B.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D1B.bam \ 
/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/H1B.bam \
-o outdir -r /home/mzar0002/pg32_scratch/db/SemiBin_db -p 12 \
&> /home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/log/semibin_multisamplebinning_coassembly1/log.log
```

But I got this error:
```
2023-08-08 21:54:19 m3s101 SemiBin[32196] INFO Binning for short_read
2023-08-08 21:54:19 m3s101 SemiBin[32196] INFO SemiBin will run in self supervised mode
2023-08-08 21:54:54 m3s101 SemiBin[32196] INFO Did not detect GPU, using CPU.
2023-08-08 21:55:01 m3s101 SemiBin[32196] INFO Generating training data...
2023-08-08 21:55:12 m3s101 SemiBin[32196] INFO Calculating coverage for every sample.
2023-08-08 21:55:18 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D1R.bam
2023-08-08 21:55:18 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/H1B.bam
2023-08-08 21:55:18 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D1B.bam
2023-08-08 21:55:18 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D5R.bam
2023-08-08 21:55:18 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D4B.bam
2023-08-08 21:55:18 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D3B.bam
2023-08-08 21:55:18 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/H4B.bam
2023-08-08 21:55:19 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/H2B.bam
2023-08-08 21:55:20 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D5B.bam
2023-08-08 21:55:21 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/H3B.bam
2023-08-08 21:55:21 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/D2B.bam
2023-08-08 21:55:21 m3s101 SemiBin[32196] INFO Processed:/home/mzar0002/ie79_scratch/Zarul/am/workflow/bin_metagenomes/results/bowtie2_mapreads/coassembly1/H5B.bam
2023-08-08 22:23:44 m3s101 SemiBin[32196] INFO Start training from one sample.
2023-08-08 22:24:04 m3s101 SemiBin[32196] INFO Training model...
^M  0%|          | 0/15 [00:00<?, ?it/s]2023-08-08 22:24:06 m3s101 SemiBin[32196] INFO Generate training data of 0:
^M  0%|          | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/fs03/ps45/Zarul/am/workflow/bin_metagenomes/.snakemake/conda/1beef34c31de50efa168463f32486711_/bin/SemiBin2", line 10, in <module>
    sys.exit(main2())
  File "/fs03/ps45/Zarul/am/workflow/bin_metagenomes/.snakemake/conda/1beef34c31de50efa168463f32486711_/lib/python3.10/site-packages/SemiBin/main.py", line 1455, in main2
    single_easy_binning(
  File "/fs03/ps45/Zarul/am/workflow/bin_metagenomes/.snakemake/conda/1beef34c31de50efa168463f32486711_/lib/python3.10/site-packages/SemiBin/main.py", line 1159, in single_easy_binning
    training(logger, None,
  File "/fs03/ps45/Zarul/am/workflow/bin_metagenomes/.snakemake/conda/1beef34c31de50efa168463f32486711_/lib/python3.10/site-packages/SemiBin/main.py", line 1007, in training
    model = train_self(output,
  File "/fs03/ps45/Zarul/am/workflow/bin_metagenomes/.snakemake/conda/1beef34c31de50efa168463f32486711_/lib/python3.10/site-packages/SemiBin/self_supervised_model.py", line 115, in train_self
    train_loader = DataLoader(
  File "/fs03/ps45/Zarul/am/workflow/bin_metagenomes/.snakemake/conda/1beef34c31de50efa168463f32486711_/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/fs03/ps45/Zarul/am/workflow/bin_metagenomes/.snakemake/conda/1beef34c31de50efa168463f32486711_/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

Not really sure what is going on..

**Comment by LaurenHuet** [comment]
I'm getting this same error on coassembly

**Comment by psj1997** [comment]
Hi

Can you help to check the data.csv file generated from SemiBin? It seems the data.csv generated from SemiBin is empty.

Sincerely
Shaojun

**Comment by luispedro** [comment]
We just released version 2, which includes a more error checking and better diagnostics; so I am closing this here, but please feel free to re-open if it still relevant.
