### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by susheelbhanu** [BigDataBiology/SemiBin#155]
Hi, 

I'm trying the `multibinning` and am getting the below error:

```bash
2024-02-25 22:45:10 n80546.nbi.ac.uk SemiBin[66519] INFO Setting number of CPUs to 512
2024-02-25 22:45:10 n80546.nbi.ac.uk SemiBin[66519] INFO Binning for short_read
2024-02-25 22:45:10 n80546.nbi.ac.uk SemiBin[66519] INFO SemiBin will run in self supervised mode
2024-02-25 22:45:14 n80546.nbi.ac.uk SemiBin[66519] INFO Did not detect GPU, using CPU.
2024-02-25 22:45:14 n80546.nbi.ac.uk SemiBin[66519] INFO Performing multi-sample binning
2024-02-25 22:45:14 n80546.nbi.ac.uk SemiBin[66519] INFO Generating training data...
2024-02-25 22:45:15 n80546.nbi.ac.uk SemiBin[66519] INFO Calculating coverage for every sample.
Traceback (most recent call last):
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/site-packages/SemiBin/main.py", line 1494, in main2
    multi_easy_binning(
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/site-packages/SemiBin/main.py", line 1204, in multi_easy_binning
    sample_list = generate_sequence_features_multi(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/site-packages/SemiBin/main.py", line 860, in generate_sequence_features_multi
    with Pool(num_process if num_process != 0 else None) as pool:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/multiprocessing/popen_fork.py", line 65, in _launch
    child_r, parent_w = os.pipe()
                        ^^^^^^^^^
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/bin/SemiBin2", line 10, in <module>
    sys.exit(main2())
             ^^^^^^^
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/site-packages/SemiBin/main.py", line 1355, in main2
    with tempfile.TemporaryDirectory() as tdir:
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/tempfile.py", line 946, in __exit__
    self.cleanup()
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/tempfile.py", line 950, in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/tempfile.py", line 930, in _rmtree
    _shutil.rmtree(name, onexc=onexc)
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/shutil.py", line 785, in rmtree
    _rmtree_safe_fd(fd, path, onexc)
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/shutil.py", line 661, in _rmtree_safe_fd
    onexc(os.scandir, path, err)
  File "/hpc-home/kar23heg/conda_envs/decode/fa91af96c6a9d4591d14ae848b15de35_/lib/python3.12/shutil.py", line 657, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
         ^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files: '/tmp/tmp2gsn3bjm'
```

My command is as shown below:
```bash
SemiBin2 multi_easy_bin -i /ei/projects/5/542de014-1e71-4955-945a-5d2ab09567a7/scratch/susbus/results/assembly/cat_assembly_filter.fasta -b /ei/projects/5/542de014-1e71-4955-945a-5d2ab09567a7/scratch/susbus/results/bam/sample1/cat_assembly_sample1.bam /ei/projects/5/542de014-1e71-4955-945a-5d2ab09567a7/scratch/susbus/results/bam/sample2/cat_assembly_sample2.bam /ei/projects/5/542de014-1e71-4955-945a-5d2ab09567a7/scratch/susbus/results/bam/sample3/cat_assembly_sample3.bam /ei/projects/5/542de014-1e71-4955-945a-5d2ab09567a7/scratch/susbus/results/bam/sample4/cat_assembly_sample4.bam -o /ei/projects/5/542de014-1e71-4955-945a-5d2ab09567a7/scratch/susbus/results/bins/semibin
```

Any thoughts on what's going on here?

Thank you,
Susheel

**Comment by susheelbhanu** [comment]
Update: the error seems to go away if I use the `-t THREADS` flag and include additional threads for the run!

**Comment by luispedro** [comment]
The first problem was that you have 512 CPUs and SemiBin was detecting this and trying to use 512 threads, which then hit other resource constraints. I actually have seen a few reports like this and I think we should perhaps limit the number of threads to be at most the number of samples (as there are no benefits to more parallelism anyway).

Not sure what is happening in the second error, though

**Comment by psj1997** [comment]
Hi, can you help to check the files generated for sample2(data.csv, data_split.csv, cov.csv)? Thanks!

**Comment by susheelbhanu** [comment]
@psj1997 i think the necessary files are being generated.

![image](https://github.com/BigDataBiology/SemiBin/assets/9979661/ef9d4c1c-e2ae-4455-a58c-85f772e574c2)

**Comment by psj1997** [comment]
Hi,

From the files you give to me. I do not find any issues. Can you show me the files for sample2? I think the error you show me is for sample2.

**Comment by susheelbhanu** [comment]
Hi @psj1997 

below attached are the sample2 files. 
thank you!

[model.h5.txt](https://github.com/BigDataBiology/SemiBin/files/14521583/model.h5.txt)
[sample2.fa.txt](https://github.com/BigDataBiology/SemiBin/files/14521584/sample2.fa.txt)
[data (1).csv](https://github.com/BigDataBiology/SemiBin/files/14521560/data.1.csv)
[data_split (1).csv](https://github.com/BigDataBiology/SemiBin/files/14521561/data_split.1.csv)
[data_cov (1).csv](https://github.com/BigDataBiology/SemiBin/files/14521562/data_cov.1.csv)

**Comment by susheelbhanu** [comment]
Yes, it is. These are test samples from a small dataset.

**Comment by psj1997** [comment]
I think the reason is that it is to small, so there no output. 
You can set `--minfasta-kbs 0 ` to output  all bins.

**Comment by susheelbhanu** [comment]
That worked perfectly, thank you very much!
