### ISSUE TITLE
special character in sample names 

### ISSUE THREAD

**Issue by gjordaopiedade** [BigDataBiology/SemiBin#156]
Hello!

I have run into a similar issue to this one https://github.com/BigDataBiology/SemiBin/issues/68, which I see it was solved in version 0.6 for Semibin. Perhaps the issue is there again with Semibin2

I am running SemiBin2 version 2.0.2 and having a similar error in the training part. Perhaps the issue is there again with Semibin2

for the sample 157633_2210271-17-02-22_METAG (I guess not the best sample name!), I get the following error and then the programs exits:

> 2024-02-23 08:11:59 tcn65.local.snellius.surf.nl SemiBin[349242] INFO Running generating cannot-link file for 157633_2210271
> 2024-02-23 08:11:59 tcn65.local.snellius.surf.nl SemiBin[349242] INFO Training model and clustering for 157633_2210271.
> 2024-02-23 08:11:59 tcn65.local.snellius.surf.nl SemiBin[349242] INFO Start training from one sample.
> 2024-02-23 08:11:59 tcn65.local.snellius.surf.nl SemiBin[349242] INFO Training model...
> 
>   0%|          | 0/15 [00:00<?, ?it/s]2024-02-23 08:11:59 tcn65.local.snellius.surf.nl SemiBin[349242] INFO Generate training data of 0:
> 
>   0%|          | 0/15 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/home/mendelab/.conda/envs/binning_pipe/bin/SemiBin2", line 10, in <module>
>     sys.exit(main2())
>   File "/home/mendelab/.conda/envs/binning_pipe/lib/python3.10/site-packages/SemiBin/main.py", line 1494, in main2
>     multi_easy_binning(
>   File "/home/mendelab/.conda/envs/binning_pipe/lib/python3.10/site-packages/SemiBin/main.py", line 1253, in multi_easy_binning
>     training(logger, None, args.num_process,
>   File "/home/mendelab/.conda/envs/binning_pipe/lib/python3.10/site-packages/SemiBin/main.py", line 1018, in training
>     model = train_self(output,
>   File "/home/mendelab/.conda/envs/binning_pipe/lib/python3.10/site-packages/SemiBin/self_supervised_model.py", line 115, in train_self
>     train_loader = DataLoader(
>   File "/home/mendelab/.conda/envs/binning_pipe/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
>     sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
>   File "/home/mendelab/.conda/envs/binning_pipe/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
>     raise ValueError("num_samples should be a positive integer "
> ValueError: num_samples should be a positive integer value, but got num_samples=0
> 

Thank you for developing and keeping Semibin!
Best wishes,

**Comment by gjordaopiedade** [comment]
Sorry! I found the issue on my side!
It has to do with the script we use to deal with the assembly separator prior to SemiBin2
