### ISSUE TITLE
Training step problem

### ISSUE THREAD

**Issue by heavennew** [BigDataBiology/SemiBin#164]
Hello, 

I had a problem when I did the multi-sample binning. The error information is below，

2024-05-28 00:44:40 localhost.localdomain SemiBin[102770] INFO Setting number of CPUs to 64
2024-05-28 00:44:40 localhost.localdomain SemiBin[102770] INFO Binning for short_read
2024-05-28 00:44:40 localhost.localdomain SemiBin[102770] INFO SemiBin will run in self supervised mode
2024-05-28 00:44:55 localhost.localdomain SemiBin[102770] INFO Did not detect GPU, using CPU.
2024-05-28 00:44:55 localhost.localdomain SemiBin[102770] INFO Performing multi-sample binning
2024-05-28 00:44:55 localhost.localdomain SemiBin[102770] INFO Generating training data...
2024-05-28 00:47:01 localhost.localdomain SemiBin[102770] INFO Calculating coverage for every sample.
2024-05-28 02:03:22 localhost.localdomain SemiBin[102770] INFO Processed: 1_sample.mapped.sorted.bam
2024-05-28 02:03:22 localhost.localdomain SemiBin[102770] INFO Processed: 2_sample.mapped.sorted.bam
2024-05-28 02:38:16 localhost.localdomain SemiBin[102770] INFO Training model and clustering for L1_contig_1000@L1.
2024-05-28 02:38:16 localhost.localdomain SemiBin[102770] INFO Start training from a single sample.
2024-05-28 02:38:31 localhost.localdomain SemiBin[102770] INFO Training model...
^M  0%|          | 0/15 [00:00<?, ?it/s]^M  0%|          | 0/15 [00:30<?, ?it/s]
Traceback (most recent call last):
  File "/data/ang/.conda/envs/SemiBin2/bin/SemiBin2", line 10, in <module>
    sys.exit(main2())
             ^^^^^^^
  File "/data/ang/.conda/envs/SemiBin2/lib/python3.12/site-packages/SemiBin/main.py", line 1610, in main2
    multi_easy_binning(
  File "/data/ang/.conda/envs/SemiBin2/lib/python3.12/site-packages/SemiBin/main.py", line 1349, in multi_easy_binning
    training(logger, None, args.num_process,
  File "/data/ang/.conda/envs/SemiBin2/lib/python3.12/site-packages/SemiBin/main.py", line 1126, in training
    model = train_self(logger,
            ^^^^^^^^^^^^^^^^^^
  File "/data/ang/.conda/envs/SemiBin2/lib/python3.12/site-packages/SemiBin/self_supervised_model.py", line 108, in train_self
    dataset = feature_Dataset(train_input_1, train_input_2, train_labels)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/ang/.conda/envs/SemiBin2/lib/python3.12/site-packages/SemiBin/semi_supervised_model.py", line 120, in __init__
    assert len(embedding1) == len(embedding2)
AssertionError

Do you know how to fix it?

**Comment by luispedro** [comment]
Thanks for the report.

Can you tell us what was the command that you ran?

**Comment by heavennew** [comment]
the command:
SemiBin multi_easy_bin -i concatenated.fa.gz -b *sample.mapped.sorted.bam -o easy_multi_sample_output --ml-threshold 30

**Comment by luispedro** [comment]
Sorry for the long delay, but `--ml-threshold 30` seems very unreasonaby low (arguably, we should warn about that or did you mean `--ml-threshold 3000`?). Also, coul you upgrade to `SemiBin2`?

**Comment by luispedro** [comment]
Is `L1_contig_1000@L1` your sample? Is it possible that it has a single contig?

**Comment by luispedro** [comment]
The `AssertionError` (`len(embedding1) == len(embedding2)`) during training in `multi_easy_bin` is consistent with a sample having too little usable data: with `--ml-threshold 30` (much lower than the default) and the sample named in the log (`L1_contig_1000@L1`) possibly containing very few contigs, the must-link pairs can end up empty or unbalanced. We asked for more details on this in 2025 but did not hear back, and the report is against an old version, so we are closing this for now.

Note that multi-sample binning does not yet check up front for samples with no usable contigs (this is done for single-sample binning since 2.4.1), so the error message there is still not helpful. If you can reproduce this with the current release (2.5.0), please reopen and share the command, the number of contigs in the failing sample, and whether `--ml-threshold` was really meant to be 30 (rather than, e.g., 3000).

— Claude (on behalf of Luis)

**Comment by luispedro** [comment]
Update: multi-sample binning now has the same early check as single-sample binning. `multi_easy_bin` and `generate_sequence_features_multi` stop up front if any sample has no contig long enough to reach the must-link threshold, with a message listing the affected samples (33ba274, https://github.com/BigDataBiology/SemiBin/commit/33ba274). It will be part of the next release, so this kind of failure in training now gives a clear message. (This issue stays closed; please open a new one if you see something different.)

— Claude (on behalf of Luis)
