### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by francesco-ricci** [BigDataBiology/SemiBin#177]
Hello

I am trying to run the code:

SemiBin2 single_easy_bin -i assembly/megahit/coassembly/coassembly.contigs_renamed.fa -b mapping/bam/cobinning/*.sorted.bam -o binning/Semibin2 

I think there's a problem with the coassembly file cause I get the following error:

2024-09-15 17:13:30 m3v105 SemiBin[1374182] INFO Setting number of CPUs to 128
2024-09-15 17:13:30 m3v105 SemiBin[1374182] INFO Binning for short_read
2024-09-15 17:13:30 m3v105 SemiBin[1374182] INFO SemiBin will run in self supervised mode
2024-09-15 17:13:36 m3v105 SemiBin[1374182] INFO Did not detect GPU, using CPU.
2024-09-15 17:13:41 m3v105 SemiBin[1374182] INFO Generating training data...
2024-09-15 17:21:30 m3v105 SemiBin[1374182] INFO Calculating coverage for every sample.
2024-09-15 17:21:50 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/Blank-3_L7_-to-contigs.sorted.bam
2024-09-15 17:25:12 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/FR2A1_L7_-to-contigs.sorted.bam
2024-09-15 17:25:52 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/FR2A2_L7_-to-contigs.sorted.bam
2024-09-15 17:26:16 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/FR2A3_L7_-to-contigs.sorted.bam
2024-09-15 17:26:16 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/FR2B1_L7_-to-contigs.sorted.bam
2024-09-15 17:26:16 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/FR2B2_L7_-to-contigs.sorted.bam
2024-09-15 17:26:16 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/FR2B3_L7_-to-contigs.sorted.bam
2024-09-15 17:26:16 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/FR2C1_L7_-to-contigs.sorted.bam
2024-09-15 17:26:16 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/FR2C2_L7_-to-contigs.sorted.bam
2024-09-15 17:26:16 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/FR2C3_L7_-to-contigs.sorted.bam
2024-09-15 17:26:16 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/SWSC1-1_L7_-to-contigs.sorted.bam
2024-09-15 17:26:16 m3v105 SemiBin[1374182] INFO Processed: mapping/bam/cobinning/SWSC2-1_L7_-to-contigs.sorted.bam
2024-09-15 17:26:22 m3v105 SemiBin[1374182] INFO Start training from a single sample.
2024-09-15 17:26:25 m3v105 SemiBin[1374182] INFO Training model...
^M  0%|          | 0/15 [00:00<?, ?it/s]/home/fricci/rp24/fra/software/miniconda3/envs/SemiBin/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3904: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/fricci/rp24/fra/software/miniconda3/envs/SemiBin/lib/python3.12/site-packages/numpy/_core/_methods.py:149: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret / rcount
^M  0%|          | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/fricci/rp24/fra/software/miniconda3/envs/SemiBin/bin/SemiBin2", line 10, in <module>
    sys.exit(main2())
             ^^^^^^^
  File "/home/fricci/rp24/fra/software/miniconda3/envs/SemiBin/lib/python3.12/site-packages/SemiBin/main.py", line 1600, in main2
    single_easy_binning(
  File "/home/fricci/rp24/fra/software/miniconda3/envs/SemiBin/lib/python3.12/site-packages/SemiBin/main.py", line 1279, in single_easy_binning
    training(logger, None,
  File "/home/fricci/rp24/fra/software/miniconda3/envs/SemiBin/lib/python3.12/site-packages/SemiBin/main.py", line 1126, in training
    model = train_self(logger,
            ^^^^^^^^^^^^^^^^^^
  File "/home/fricci/rp24/fra/software/miniconda3/envs/SemiBin/lib/python3.12/site-packages/SemiBin/self_supervised_model.py", line 109, in train_self
    train_loader = DataLoader(
                   ^^^^^^^^^^^
  File "/home/fricci/rp24/fra/software/miniconda3/envs/SemiBin/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fricci/rp24/fra/software/miniconda3/envs/SemiBin/lib/python3.12/site-packages/torch/utils/data/sampler.py", line 144, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0

The coassembly file looks like this:

>k127_4310605_flag_1_multi_3.0000_len_1046
GCTTCGTCCAGCGCGGCGCGCCCGATCCCCACCGCGTTTGCGGCGATCACCGGCCGCCCCGCGTTGAAGGTCGCCATCGCCGCCTTGAAGCCGGCCTTGCGCTCGTAGCGCTCCTCGCCCCCCAGCAGGTTCGCGGCGGGGACCCGCACGTCCTCGAGCGGAAAGGAGCAGGATTCGTAGGCCTTGAGGCCCAGCTTCTTCTCGATCTTGAACGGGCCGAGTCCGGGGGTGTCTCGCTCGACGAAGAAGGCGCGCTGGGCCGCACGGCCCTGACTCGGGTCGAGGGTCGCCTGGACCAGGATCCAATCGGAACGCGCCGCCGATCCGATAAAGCATTTCGCCCCGTTCAGGATCCAGTGGTCGCCGTCTTTGCGCGCGCGTGTCTGAATCGCCGCGGCATCGGAGCCGGCCCCGGGCTCCGTCATCGCGAAGCAGGCCCAGCGCGGTCGATCCGGCTCGAGGAAGGGACCGAGAAAGCGCTCCTTCTGCTCCTGCGTCCCCATCCCGAGGACGCTCTGCTGAGGCAGGCCCGGGCCCGGAGTCGCGACCACAACGCCGCGATCCCAGTACGCGAACTCCTCCGCGAGGAGCAGCCGAGACATCGTCGCCGAGCCGGATCTGGCTGAGGAGCGGCGTTTCGATTTCCTCTCGCTGTCCGGGCGCCATTGCGTCCGGCCGTCGCCTCGCTCGAGACACTTCTCGAAGAAGGGGTGACCCACCGGAATCGGCGCCGACGCCCGATCGGACTCGAGGCCGGCTGGGCGCACGTGATCGCGACCCCAGATCCGCAATACGGCAAGTCTCTCCCGCGTGGCTTCGTCGATCGAGAAGTCCACTAGAGCGCCTCCCCCGTACAGAGGTCGAGGGGACTATCAGCTTCGCACAGACTTCGACCCGCCTCATCGATCGCGGCGTCGAAGCCGCCCAGCAGAAGGCCGAGCGCCCGCGCCTCGCGCATGTGCTTCTCGACGGGGTAATCCTGCATGAATCCGTGCACGCACAGGATCTGTACGGCGTTGGGACCGACGAAGGTCGACGCCTCCGCC
>k127_2634258_flag_1_multi_3.0000_len_1330
GGTGCTGATCGACTGCAACGACGTCATCTGCCACGTCTTCACCGAAGAAGCGCGCGCGACCTACGACCTCGAACGCCTCTGGGCGGACGCGAAGCCGATCGAGCTCGATCTCCCGCAGGCCGCGGGAGAAGTCGCTTGAGCGCGGCCGGCGACGACGCGAAGGGCCCCGTCGTACTCGTCGTCCTCGACGGCTTCGGCCTCGGCGACGGTGGCGACGCCGATGCGACGGCGGCTGCGCACGGCCCCTTCTTCGACGAAGTCGTTCAGCGCTACCCCCATGCGCAGCTCGAAACCTCGGGCGAAGCGGTGGGTCTGCCCCCGGGCCAGATGGGCAACTCCGAAGTCGGCCACATGACGATGGGCGCCGGTCGCATCATCGAGCAGGACATGACGCGCATCACGCGCGAACTCGCCGAAGGCGCGATGGAGACCAACGAGGTACTCCGCTCCGCGCTCGATGCCGTCGCGAACACCGGCGGCACGCTGCACCTGATCGGCTTGCTGAGTGACGGCGGCGTCCACAGCCACCAGGAGCATCTCTACGCCATCCTCGAGAGTTGCGGACGCCGCGGAGTTTCCGCCGCCGTTCACGCGCTGCTCGATGGCCGAGACACGCCGCCGAAATCGGGCAGGGGCTACATCGAGCAACTGCTGCCCGTCTGCGAAGCCAACGGTGCGCAGATCGCAACCGTGATAGGTCGCTACTACGCCATGGACCGCGACAACCGCTGGGAACGCGTCGGCCTGGCGTACAACGCGATGGTGCACGGCAAGGGGGAGCTCGCGCCGGATGCCGTGACAGCCGTTTCGAGCGCCTATGCGCGCGAGGAAACCGACGAGTTCGTCGCGCCGACATTCATCGAGGGCGGCCGTCGTATCTCGGATGGCGATGCCGTCCTGTTCTTCAACTTCCGCGCCGACCGCGCGCGAGAACTCACCAACGCACTCACGGGCGTACTGCCGAAGCACTACGAGGGCGAACTCGACCGCGGTACGGCGCCGAAGCTCGCCCGCTTCGTCTGCTTGACCGAATACGACGCCGAGTTCGGCCTGCCCGTCGCTTTCGGCTCGGACACGACGAGGAACATCCTCGGCGAAGTGATCGCCGCGCACGGGCTCGAGCAACTCCGCACCGCCGAGACCGAGAAGTACGCGCACGTCACGTTCTTCTTCAACGCGGGCGTCGAAGAGCCCTTTCCGGGTGAGGACCGCGTGCTGATTCCGTCACCGCGCGACGTCGATACCTACGACCACAAGCCCGAGATGAGTGCGCTGCAACTCACCGACACCCTGATCGGTCGCATCGAGGAAGGCGGCTACGACTTCGTCC
>k127_10896213_flag_1_multi_4.0000_len_1085
GAGCATGCACCGTTTGGACGACTAGAGCTCGATCTGTGCGTCAGTGCATTTCGAGCCGCGGATCGGCCGAGCCTGGTGCGCACTGCAAACGATTCGCCAACAGAGATTCGCAATGCGCTTGACAGCGGAGCTACCGGCATTCTCGTGCCGCATGTCACGAGCGCAGAGCAAGCAGCGGCGATTGCTAAGGCTGCTCACTTCGGCGATGGCGGTCGCGGCTATGCCGGGTCATCACGTGCCGCCGAATACACAACGAAGTCCATGGCCGATCACATTGCCGACAGTCGTGAACAAACTACGGTTGTCGTGCAAATTGAGGACATTGCCGCTCTAGATCATGTCGCTCAGATTGCAGCCGTCGACGGCGTGGATGCTCTGTTTGTCGGCCGTTTCGATCTCGCCGTGGCAATGCAGAAGAGTCCGTCGGATACGGACGTCATTGCGACCGTTCGGGATATTTGTGTGGCAGGGCGAAGTGCTGGCACCGCGGTTGGCATGTTTACGGCAAACCTGGATGAGATCCCCGACTGGCGCGACGCGGGCGCCAACCTTTTCATGCTGAGTTCCGACCAGTCGATGCTGCTGACGGGAGCGAACGCGCGGGCAAAATCAACCCGTCCGTAATGGGGACATTCTGCTTTTTTTAAGAAAAGCAGAATGTCCCCATTACAGACGGTAAAAGTCGCGTGCCGTGTCTCCAAAAATCCGCGCTTGTTCGTGTTCGCTTAATACCGTCGTGATTGCTTCGTACGCACTCCACACCTGGTTGTAAGTCGAATGCAACTTGTCGACCGGAAAGTTCGACCCGAACATGCAGCGCTCAACGCCGAAGTTCTCAATGCAGGATTCGACGATCGGACGAATCGAATCAACCGTCCAGTCGTGATCGAACATGCCGAGCCCGGAAATCTTGCAATACACGTTGGGTAGCGATGCCAGCAGGCGAAGACCATCACGCCACGACTCGAGTCCTAGCTTGGACTGGTCCCACGGTGAGCCGCAGTGACAAAGCGCGATATCTGTATCGGGAGTATCCGCCAACACCTCGGCGATGCGCGGTACCTGTCCCGGCGTCAGCTGTAAAT

Any help would be much appreciated, thank you!
Francesco

**Comment by francesco-ricci** [comment]
Hello

I fixed this, the problem was actually both my contig and bam files. I prepared them again following the provided instructions and now the software seems to run. Do you have an idea of how long should I expect the model training to run on a ~3GB contigs dataset?

Thanks
Francesco
