### ISSUE TITLE
Is a minimal contig length required? 

### ISSUE THREAD

**Issue by SilasK** [BigDataBiology/SemiBin#33]
I got the following error in SemiBin predict_taxonomy

```
Traceback (most recent call last):
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/276d10745f3e7a40761b5d1f8bc460cc/bin/SemiBin", line 10, in <module>
    sys.exit(main())
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/276d10745f3e7a40761b5d1f8bc460cc/lib/python3.7/site-packages/SemiBin/main.py", line 842, in main
    binned_short, must_link_threshold, contig_length_dict, contig_dict = process_fasta(args.contig_fasta)
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/276d10745f3e7a40761b5d1f8bc460cc/lib/python3.7/site-packages/SemiBin/utils.py", line 354, in process_fasta
    binned_short = contig_bp_2500 / whole_contig_bp < 0.05
```

By the way, I can imagine that different binners might have different performances, simply by using different min contig lengths, as short contigs are more difficult to bin correctly.

**Comment by SilasK** [comment]
My input files are strange. Probably it's due to this.
