### ISSUE TITLE
Error in unzip_fasta

### ISSUE THREAD

**Issue by SilasK** [BigDataBiology/SemiBin#42]
I got the following error with Semibin 0.3 (conda)

Command: 
````

SemiBin train  --input-fasta Cobinning/filtered_contigs/shRTF1.fasta.gz  --input-bam Cobinning/mapping/shRTF8.sorted.bam Cobinning/mapping/shRTF2.sorted.bam Cobinning/mapping/shHF7.sorted.bam Cobinning/mapping/shRTC3.sorted.bam Cobinning/mapping/shHC1.sorted.bam Cobinning/mapping/shRTC1.sorted.bam  --output Cobinning/SemiBin/samples/shRTF1  --threads 12  --data Cobinning/SemiBin/samples/shRTF1/data.csv  --data-split Cobinning/SemiBin/samples/shRTF1/data_split.csv  --cannot-link Cobinning/SemiBin/samples/shRTF1/cannot/cannot_bin.txt  --mode single   --epoches 20 --mode single   2> log/semibin/train/shRTF1.log

```
Log: 
```

Traceback (most recent call last):
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/1cec50d1b28e8ec0fae5f1275adeb023/bin/SemiBin", line 10, in <module>
    sys.exit(main())
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/1cec50d1b28e8ec0fae5f1275adeb023/lib/python3.8/site-packages/SemiBin/main.py", line 888, in main
    contig_name = unzip_fasta('gz', args.contig_fasta)
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/1cec50d1b28e8ec0fae5f1275adeb023/lib/python3.8/site-packages/SemiBin/utils.py", line 369, in unzip_fasta
    contig_name = contig_path.replace(".gz", "")
AttributeError: 'list' object has no attribute 'replace'
```

**Comment by SilasK** [comment]
semibin v0.3 has an obvious bug for .gz file used in SemiBin train. This part has been removed in #BigDataBiology/SemiBin@ea040d4#diff-80d9229f949ec2902de7f43d3801ecfe799b25a20691bdd0c10eb96694fcaf13 . But v3.0 still kept this, where in line 871 and 874 (SemiBin/main.py) the list varibale args.contig_fasta shall be replaced with the item contig in the loop.

from https://github.com/metagenome-atlas/atlas/pull/365

**Comment by psj1997** [comment]
Thanks for bug report. This is an bug when processing zipped fasta file. We have fixed this, you can try this installing from the source code. We will update the anaconda version later.

Sincerely
Shaojun

**Comment by SilasK** [comment]
For pipeline developments, I rely on conda packages. Please close the issue when you have a new release..
