### ISSUE TITLE
seg fault in predict taxonomy

### ISSUE THREAD

**Issue by SilasK** [BigDataBiology/SemiBin#46]
Any idea what this error coud be due?

Id does just been I cannot write enough files

```
export TMPDIR=/local_scratch/silaskieser &> logs/semibin/predict_taxonomy/DNA8-2.log ;SemiBin predict_taxonomy  --input-fasta Cobinning/filtered_contigs/DNA8-2.fasta  --threads 8  --output Cobinning/SemiBin/DNA8-2  --cannot-name cannot_bin  --reference-db /scratch/project_2004930/databases/SemiBin_GTDB/GTDB
```

```
MMseqs Version:                         13.45111
ORF filter                              1
ORF filter e-value                      100
ORF filter sensitivity                  2
LCA mode                                3
Taxonomy output mode                    0
Majority threshold                      0.5
Vote mode                               1
LCA ranks
Column with taxonomic lineage           1
Compressed                              0
Threads                                 8
Verbosity                               3
Taxon blacklist                         12908:unclassified sequences,28384:other sequences
Substitution matrix                     nucl:nucleotide.out,aa:blosum62.out
Add backtrace                           false
Alignment mode                          1
Alignment mode                          0
Allow wrapped scoring                   false
E-value threshold                       1
Seq. id. threshold                      0
Min alignment length                    0
Seq. id. mode                           0
Alternative alignments                  0
Coverage threshold                      0
Coverage mode                           0
Max sequence length                     65535
Compositional bias                      1
Max reject                              5
Max accept                              30
Include identical seq. id.              false
Preload mode                            0
Pseudo count a                          1
Pseudo count b                          1.5
Score bias                              0
Realign hits                            false
Realign score bias                      -0.2
Realign max seqs                        2147483647
Gap open cost                           nucl:5,aa:11
Gap extension cost                      nucl:2,aa:1
Zdrop                                   40
Seed substitution matrix                nucl:nucleotide.out,aa:VTML80.out
Sensitivity                             2
k-mer length                            0
k-score                                 2147483647
Alphabet size                           nucl:5,aa:21
Max results per query                   300
Split database                          0
Split mode                              2
Split memory limit                      0
Diagonal scoring                        true
Exact k-mer matching                    0
Mask residues                           1
Mask lower case residues                0
Minimum diagonal score                  15
Spaced k-mers                           1
Spaced k-mer pattern
Local temporary path
Rescore mode                            0
Remove hits by seq. id. and coverage    false
Sort results                            0
Mask profile                            1
Profile E-value threshold               0.001
Global sequence weighting               false
Allow deletions                         false
Filter MSA                              1
Maximum seq. id. threshold              0.9
Minimum seq. id.                        0
Minimum score per column                -20
Minimum coverage                        0
Select N most diverse seqs              1000
Min codons in orf                       30
Max codons in length                    32734
Max orf gaps                            2147483647
Contig start mode                       2
Contig end mode                         2
Orf start mode                          1
Forward frames                          1,2,3
Reverse frames                          1,2,3
Translation table                       1
Translate orf                           0
Use all table starts                    false
Offset of numeric ids                   0
Create lookup                           0
Add orf stop                            false
Overlap between sequences               0
Sequence split mode                     1
Header split mode                       0
Chain overlapping alignments            0
Merge query                             1
Search type                             0
Search iterations                       1
Start sensitivity                       4
Search steps                            1
Exhaustive search mode                  false
Filter results during exhaustive search 0
Strand selection                        1
LCA search mode                         false
Disk space limit                        0
MPI runner
Force restart with latest tmp           false
Remove temporary files                  false

extractorfs Cobinning/SemiBin/DNA8-1/contig_DB /tmp/silaskieser/8073032/tmpd2qvtmf_/10702455619826666220/orfs_aa --min-length 30 --max-length 32734 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --translate 1 --use-all-table-starts 0 --id-offset 0 --create-lookup 0 --threads 8 --compressed 0 -v 3

[==================================================Can not write to data file i
Can not write to data file p
Can not write to data file m
Can not write to data file t
*** Error in `mmseqs': free(): corrupted unsorted chunks: 0x0000563c515a03e0 ***
*** Error in `mmseqs': free(): corrupted unsorted chunks: 0x0000563c515a6520 ***
*** Error in `mmseqs': double free or corruption (!prev): 0x0000563c515a03e0 ***
Can not write to data file /
/tmp/silaskieser/8073032/tmpd2qvtmf_/10702455619826666220/taxpercontig.sh: line 32: 62091 Segmentation fault      "$MMSEQS" extractorfs "${CONTIGS_DB}" "${ORFS_DB}" ${EXTRACT_ORFS_PAR}
Error: extractorfs died
Traceback (most recent call last):
  File "/scratch/project_2004930/databases/conda_envs/eaa4f62200c6ba0658b6243854907334/bin/SemiBin", line 10, in <module>
    sys.exit(main())
  File "/scratch/project_2004930/databases/conda_envs/eaa4f62200c6ba0658b6243854907334/lib/python3.8/site-packages/SemiBin/main.py", line 912, in main
    predict_taxonomy(
  File "/scratch/project_2004930/databases/conda_envs/eaa4f62200c6ba0658b6243854907334/lib/python3.8/site-packages/SemiBin/main.py", line 408, in predict_taxonomy
    subprocess.run(
  File "/scratch/project_2004930/databases/conda_envs/eaa4f62200c6ba0658b6243854907334/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'taxonomy', 'Cobinning/SemiBin/DNA8-1/contig_DB', '/scratch/project_2004930/databases/SemiBin_GTDB/GTDB', 'Cobinning/SemiBin/DNA8-1/mmseqs_contig_annotation/mmseqs_contig_annotation', '/tmp/silaskieser/8073032/tmpd2qvtmf_', '--tax-lineage', '1', '--threads', '8']' returned non-zero exit status 1.

```

**Comment by SilasK** [comment]
tmp on my cluster nodes was too small

**Comment by fplaza** [comment]
Same problem here!
Could you add an option to specify temporary directory?

**Comment by luispedro** [comment]
@fplaza : I opened a new issue (#57) specifically about adding an option for the temporary directory. In the meanwhile, you can use the `$TMPDIR` environmental variable to specify it.
