### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by ckeuschn** [BigDataBiology/SemiBin#91]
Hi,

I am curious to test SemiBin on my current dataset, but  did run into this error:

>2022-04-29 11:21:53,885 - Start generating kmer features from fasta file.
2022-04-29 11:47:38,009 - Start binning.
Traceback (most recent call last):
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/bin/SemiBin", line 10, in <module>
    sys.exit(main())
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/lib/python3.9/site-packages/SemiBin/main.py", line 1035, in main
    single_easy_binning(
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/lib/python3.9/site-packages/SemiBin/main.py", line 860, in single_easy_binning
    binning(logger, args.num_process, data_path,
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/lib/python3.9/site-packages/SemiBin/main.py", line 805, in binning
    cluster(
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/lib/python3.9/site-packages/SemiBin/cluster.py", line 108, in cluster
    embedding = model.embedding(x.float()).detach().cpu().numpy()
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/lib/python3.9/site-packages/SemiBin/semi_supervised_model.py", line 89, in embedding
    return self.encoder1(input)
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/lib/python3.9/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ampere/ckeuschn/anaconda3/envs/SemiBin/lib/python3.9/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (94214x391 and 136x512)

Any idea what's happening here?

Thanks,
Christoph

**Comment by psj1997** [comment]
Hi, Christoph

Can you share me the information like the command you have used and how many samples you use in the binning?

Sincerely
Shaojun

**Comment by ckeuschn** [comment]
Sure, 

command was:

>SemiBin  single_easy_bin \
    --input-fasta 03_CONTIGS/contigs.fa \
    --input-bam 04_MAPPING/*.bam \
    --environment soil \
    --output SemiBin_output

and I did run it with 277 samples.

Thanks for the fast reply!

**Comment by psj1997** [comment]
Thanks!

The reason is that our pretrained model (--environment soil) can just be used in the single-sample binning due to the algorithm design. If you have 277 samples, you can train a model from your data and bin the contigs. So you can just remove the --environment parameter. 

Sincerely
Shaojun

**Comment by ckeuschn** [comment]
Great, thanks!

**Comment by luispedro** [comment]
I am going to re-open as this is a usability issue (also tagged it `bad-error-message`)

@ckeuschn  Thanks for reporting

@psj1997 can you add some checking for this case and some better error message than `matrix sizes blah blah blah`?

**Comment by psj1997** [comment]
I have added an error message about this: `Error: provided pretrained model only used in single-sample binning!`
